### ISSUE TITLE
Is this Example working?

### ISSUE THREAD

**Issue by SanjayBandhniya** [abhinavmishra14/search-extension-demo#1] opened 2022-07-26 06:08 UTC
I am trying to run this project and searching as per given screenshot but I am not getting result.

**Comment by abhinavmishra14** [comment] 2022-07-26 13:22
Hi Sanjay
I will take a look and update you

**Comment by abhinavmishra14** [comment] 2022-07-26 17:43
hi @SanjayBandhniya 
This seems to work perfectly fine. I hope you applied the "cm:author" and "acme:copyrightYear" properties on nodes you expect to get in search result.

**Comment by abhinavmishra14** [comment] 2022-07-26 17:47
@SanjayBandhniya  This seems to work perfectly fine. I hope you applied the "cm:author" and "acme:copyrightYear" properties on nodes you expect to get in search result.  

Please see additional details below:

Properties on the nodes:
![applied-prop-example](https://user-images.githubusercontent.com/349137/181075604-c3fd6da7-f851-49ca-9b79-2a617ab5f087.jpg)

Results:
![search-author-live](https://user-images.githubusercontent.com/349137/181075723-9e78a921-aa53-46c5-835c-2e6e3e762374.png)
![search-author-sitescope](https://user-images.githubusercontent.com/349137/181075725-5fef2645-2204-471b-baf4-3d6414a081c4.png)
![search-copyright](https://user-images.githubusercontent.com/349137/181075726-2e59af4f-e648-4a18-967d-06fa0687976c.png)
![search-author](https://user-images.githubusercontent.com/349137/181075727-4f2b0bf7-a046-42ba-97fd-9c9b0e9bda69.png)

**Comment by abhinavmishra14** [comment] 2022-07-26 17:49
Not able to reproduce, closing the issue.

**Closed as not planned by abhinavmishra14** 2022-07-26 17:49 UTC
